name: initializer
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependency_overrides:
  analyzer: 7.1.0

dependencies:
  data:
    path: ../data
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  flutter_lints: 3.0.1
