name: resources
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependency_overrides:
  analyzer: 7.1.0
  
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7

dev_dependencies:
  # flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n
