name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependency_overrides:
  analyzer: 6.2.0

dependencies:
  async: ^2.11.0
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  meta: ^1.15.0
  resources:
    path: ../resources
  rxdart: ^0.27.7
  shared:
    path: ../shared
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.6.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  mocktail: ^1.0.4
  nals_lints:
    path: ../nals_lints
