name: app
description: "Chốt bất động sản"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  infinite_scroll_pagination: ^4.1.0
  async: ^2.11.0
  cached_network_image: ^3.4.1
  dartx: ^1.2.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  injectable: ^2.5.0
  rxdart: ^0.28.0
  tuple: ^2.0.2
  ##
  intl: ^0.19.0
  dio: ^5.4.0
  timezone: ^0.9.1
  pull_to_refresh: ^2.0.0
  get: ^4.6.6
  intl_utils: ^2.8.7
  local_auth: ^2.3.0
  flutter_localization: ^0.3.0
  persistent_bottom_nav_bar: ^6.2.1
  get_storage: ^2.1.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.2
  another_flushbar: ^1.12.30
  file_picker: ^8.1.7
  flutter_typeahead: 4.6.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  intl_utils: ^2.8.7

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/vi.json
  
  fonts:
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Montserrat-Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 200
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Lato-Medium
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 400
    - family: Lato-Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
    - family: Lato-SemiBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
    - family: Lato-Bold
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 600
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Black.ttf
          weight: 800
        - asset: assets/fonts/Lato-Black.ttf
          weight: 700
        # - asset: assets/fonts/Montserrat-Regular.ttf
        # - asset: assets/fonts/Montserrat-Black.ttf
        # - asset: assets/fonts/Montserrat-Bold.ttf
        # - asset: assets/fonts/Montserrat-Italic.ttf
        # - asset: assets/fonts/SourceSerif4-Thin.ttf
        # - asset: assets/fonts/Montserrat-Light.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

dependency_overrides:
  intl: 0.19.0
