name: app
description: "Chốt bất động sản"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  infinite_scroll_pagination: ^4.1.0
  async: ^2.11.0
  cached_network_image: ^3.4.1
  dartx: ^1.2.0
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  injectable: ^2.5.0
  rxdart: ^0.28.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml

flutter:

  uses-material-design: true
  assets:
    - assets/images/
