name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 7.1.0

dependencies:
  android_id: ^0.4.0
  async: ^2.11.0
  dartx: ^1.2.0
  decimal: ^3.0.2
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_udid: ^4.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  mime: ^1.0.6
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  rxdart: ^0.27.7
  timezone: ^0.9.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.6.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  logging: ^1.3.0
  mocktail: ^1.0.4
  nals_lints:
    path: ../nals_lints
